# Id de tag
remote_tag_id: 0x6833

#Id de anchor
anchor1_id: 0x686f
anchor2_id: 0x6866
anchor3_id: 0x6831
anchor4_id: 0x6854

#Posicion de los anchor en mm (referencias)
anchor1_x: 0
anchor1_y: 0
anchor1_z: 270

anchor2_x: 5410
anchor2_y: 4250
anchor2_z: 2150

anchor3_x: -140
anchor3_y: 4350
anchor3_z: 2160

anchor4_x: 6000
anchor4_y: 0
anchor4_z: 840
